name: "Feature request"
description: "Suggest a new feature or improvement"
title: "[Feature]:"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **We appreciate your feedback!**
        Please complete the following information to submit a feature request.

  - type: input
    id: feature_title
    attributes:
      label: "Feature Title"
      description: "Give your feature request a descriptive title."
      placeholder: "E.g., Add dark mode support."

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Describe the feature in detail."
      placeholder: "E.g., As a user, I want to be able to switch to dark mode, so I can reduce eye strain in low-light environments."

  - type: textarea
    id: use_cases
    attributes:
      label: "Use Cases"
      description: "What problems will this feature solve, or what improvements will it bring?"
      placeholder: "E.g., This feature will help users who prefer dark mode for visual comfort."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature to you?"
      options:
        - "Low"
        - "Medium"
        - "High"

  - type: input
    id: related_features
    attributes:
      label: "Related Features (Optional)"
      description: "List any existing features or issues this request relates to."
      placeholder: "E.g., Related to Issue #123"

